### ISSUE TITLE
Stuck on "Your Wallet History"

### ISSUE THREAD

**Issue by michaelharms6010** [nighthawk-apps/zcash-ios-wallet#2]
Platform: iPhone 8

Newly created wallet. Navigated to my empty wallet history, the back button does a slide transition, revealing the same wallet history page.

A minute later, my first transaction confirmed and I saw it appear in my wallet history. The back button behavior didn't change, the wallet history keeps slide transitioning away, revealing a copy of itself.

Expected behavior - The back button should take me back to the send screen.

Additionally, the single transaction I have received flickers to black occasionally, making the history look blank for a second or so.

After killing and restarting the app, the back arrow works as expected, but the transaction still flickers in the list.

**Comment by nighthawk24** [comment]
@michaelharms6010 do you have this issue? Please try again, also an alternative is to swipe down to close views, even though that might not be obvious for the users.

**Comment by michaelharms6010** [comment]
No, I haven't had the missing back arrow issue since I first installed in March.

I do still have frequent flickering of my transaction list on the "Your Wallet History" screen. My single transaction disappears, the list is solid black for a split second. Flickers are about every 15 seconds.

**Comment by nighthawk24** [comment]
This should be fixed, please reopen if it's still an issue.
