### ISSUE TITLE
Unable to send funds; error message "Authorization failed! No identities are enrolled."

### ISSUE THREAD

**Issue by Mitchellpkt** [nighthawk-apps/zcash-ios-wallet#4]
I'm unable to transfer funds from an iPhone test wallet, due to an error "Authorization Failed! No identities are enrolled." I uninstalled Nighthawk, reinstalled, and restored the wallet from seed, but the error persists (screenshot below)

Let me know if you have any questions or recommendations. I'm a big fan of Nighthawk wallet and the z2z only UI :- )

![IMG_4210](https://user-images.githubusercontent.com/21246742/113073634-b26c0180-9186-11eb-84b7-0ba56b9e0890.jpg)

**Comment by nighthawk24** [comment]
@Mitchellpkt Apologies for the delay in reply. Please try setting up security pin or biometric auth or FaceID as it is a requirement for securing/accessing the funds for Nighthawk.
